2017-08-03 09:17:15,800 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://clientapi.ipip.net/echo.php?info=1234567890 (139.162.81.62) 2.01ms
2017-08-03 09:41:32,841 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-03 17:15:09,844 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.225.197) 2.05ms
2017-08-03 17:16:16,191 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.225.197) 1.98ms
2017-08-04 04:01:51,126 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://www.qq.com/404/search_children.js (120.132.3.151) 1.98ms
