2017-08-22 12:18:06,440 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://clientapi.ipip.net/echo.php?info=1234567890 (139.162.81.62) 2.09ms
2017-08-22 15:26:45,795 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-22 15:26:45,798 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-22 22:41:07,637 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.225.196) 2.00ms
2017-08-22 22:41:12,609 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.225.196) 1.90ms
2017-08-23 00:05:26,952 - tornado.access - web.py[line:1971] - WARNING - 405 HEAD / (127.0.0.1) 2.00ms
2017-08-23 09:41:20,061 - tornado.general - web.py[line:1545] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713527 (112.74.206.16): '_xsrf' argument missing from POST
2017-08-23 09:41:20,062 - tornado.access - web.py[line:1971] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713527 (112.74.206.16) 15.09ms
2017-08-23 10:16:05,837 - tornado.general - web.py[line:1545] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713879 (119.84.8.43): '_xsrf' argument missing from POST
2017-08-23 10:16:05,838 - tornado.access - web.py[line:1971] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713879 (119.84.8.43) 36.30ms
2017-08-23 10:51:11,047 - tornado.general - web.py[line:1545] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713351 (112.74.206.16): '_xsrf' argument missing from POST
2017-08-23 10:51:11,048 - tornado.access - web.py[line:1971] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713351 (112.74.206.16) 16.53ms
2017-08-23 10:51:11,051 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-23 11:26:26,141 - tornado.general - web.py[line:1545] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713789 (112.74.206.16): '_xsrf' argument missing from POST
2017-08-23 11:26:26,142 - tornado.access - web.py[line:1971] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713789 (112.74.206.16) 15.42ms
2017-08-23 12:01:16,402 - tornado.general - web.py[line:1545] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713478 (119.84.8.43): '_xsrf' argument missing from POST
2017-08-23 12:01:16,403 - tornado.access - web.py[line:1971] - WARNING - 403 POST http://www.ceair.com/otabooking/flight-search!doFlightSearch.shtml?rand=0.815197114713478 (119.84.8.43) 33.67ms
